### ISSUE TITLE
Module doesn't delete if ttl expired

### ISSUE THREAD

**Issue by Karthikmuthupandi** [hotelde/node-cache-manager-fs#13]
Hi All,

node-cache-manager-fs doesn't delete the cache files if ttl has expired. Is there any way to remove/delete those files using this node-cache-manager-fs node module(method).

**Comment by Mar-Pfa** [comment]
Feel free to provide a pull request with this missing feature - i'll commit it and push an updated to npm. Think about making this cleanup as a backround task with low priority to prevent lowering performance of the caching routine.
kind regards
