### ISSUE TITLE
Library throws an exception when trying to recover cached values which cache files has been deleted

### ISSUE THREAD

**Issue by esteban-filardi** [hotelde/node-cache-manager-fs#17]
I had some values cached.  I wanted to "invalidate" this cached values before they've reached the end of their TTL values, so I went and deleted the content of the "cache" directory.

The result is that, when trying to get the values, an exception is being thrown indicating that the ".dat" file can't be loaded. 

errno ENOENT syscall open path diskcache/cache_1f24a906-5b4c-4357-90e4-2dba0aaa7f1f.dat

Shouldn't the library  considered that there's no value cached and attempt to retrieve a new one?
I've used other filesystem cache libraries and that is the standard behavior.

**Comment by Mar-Pfa** [comment]
hm, you're right... feel free to create a fix and a pull request, i'll asap merge and publish it

**Comment by cvipul** [comment]
Where does the library store collection in the persistent memory? For now I want to just delete that and restart the whole cache.

**Comment by Mar-Pfa** [comment]
when you look in the code you'll find in "index.js" within the first 100 rows a property:
	// internal array for informations about the cached files - resists in memory
	this.collection = {};

**Comment by Mar-Pfa** [comment]
thinking again about the initial issue from [esteban-filardi](https://github.com/esteban-filardi) -> when the cache file was deleted and the library tries to load it it's ok to throw an exception because an external source has messed around with the cache files. From my point of view the behavior is ok here
