### ISSUE TITLE
Missing parameter in get method

### ISSUE THREAD

**Issue by kfrajtak** [hotelde/node-cache-manager-fs#2]
Hi,

I am using your llibrary and got some problems to make it work in my app. I noticed that the `get` method in your code has only 2 parameters, while otherwise it has 3 (see [cache-manager-redis](https://github.com/dial-once/node-cache-manager-redis/blob/master/index.js#L90)).

Alse when invoked in cache-manager `wrap` function 3 parameters are [used ](https://github.com/BryanDonovan/node-cache-manager/blob/8fc6636a768159c8bfcf8f1eaa79b39db8ce6c02/lib/caching.js#L97)

```
 self.store.get(key, options, function(err, result) { ... }
```

When `options` is `null` then `cb` is set to `noop`:

```
DiskStore.prototype.get = function (key, cb) {
cb = typeof cb === 'function' ? cb : noop;
    ...
}
```

Should I fix it and create a pull request or can you fix it yourself?

Regards,
Karel

**Comment by amit777** [comment]
hi, i was planning on using this cache store mechanism, and i currently use the wrap method. Are you using this code with your pull request in production?

**Comment by kfrajtak** [comment]
Hi, I am not using it in a production ready app, but in my private pet
project. I can create a pull request, but it will won't be ready soon (I am
on vacation until June).
Karel

**Comment by Mar-Pfa** [comment]
in fact this issue is closed already since a longer time, latest version contains the fix
