### ISSUE TITLE
Delete operation does not support options arg

### ISSUE THREAD

**Issue by fctb12** [hotelde/node-cache-manager-fs#30]
The delete operation does not support options arg, which results in incompatibility with several caching managers such as [node-cache-manager](https://github.com/BryanDonovan/node-cache-manager). To fix this, the first few lines of the DiskStore delete operation need to be rewritten to the following.

```
DiskStore.prototype.del = function (key, options, cb) {

  if (typeof options === 'function') {
        cb = options;
        options = null;
  }
  cb = typeof cb === 'function' ? cb : noop;
```

**Comment by simlu** [comment]
Would be great to get this package updated as detailed in this issue!

It prevents us from updating node cache-manager, and we are stuck on an old version which is starting to cause us issues.

Cheers!

**Comment by Mar-Pfa** [comment]
package contains the code code with the change from fctb12 - I published a new version on npm - this fixes the issue hopefully.
If the issue still exists feel free to develop a fix and create a pull request :-)
