### ISSUE TITLE
Breaking change introduced in 1.0.5

### ISSUE THREAD

**Issue by georgecrawford** [hotelde/node-cache-manager-fs#5]
https://github.com/hotelde/node-cache-manager-fs/pull/3 is a breaking change, as calls which worked previously using `.get(key, cb)` will now never have the callback called.

`cache-manager-redis` does indeed support 3 params, but has this important fallback:

``` js
    if (typeof options === 'function') {
      cb = options;
    }
```

https://github.com/dial-once/node-cache-manager-redis/blob/master/index.js#L91-L93

**Comment by Mar-Pfa** [comment]
pull request merged, issue closed
