### ISSUE TITLE
Doesn't reinitialize with zip option enabled

### ISSUE THREAD

**Issue by sheershoff** [hotelde/node-cache-manager-fs#8]
I've fixed it here https://github.com/sheershoff/node-cache-manager-fs-binary/commit/5c9406224cf7ad46473aeb3c841c380fdaded3ed

Since the tests are failing, it's meaningless to PR a separated fix until #7 is merged.

So, one can go fetch changes or I'll come in with new PR when #7 is merged.

**Comment by Mar-Pfa** [comment]
issue is fixed in version 1.0.12
